### ISSUE TITLE
Dist folder missing?

### ISSUE THREAD

**Issue by davykenis** [michelgrootjans/explaining-flow#1]
Could it be the dist folder is missing in the repo?
Tried to clone the repo and run the program but getting bellow error:

FVFXKEY9HV29:explaining-flow davy.kenys$ npm run bundle

> kanban@1.0.0 bundle /Users/davy.kenys/Library/Mobile Documents/com~apple~CloudDocs/Intaqt/Trainingen/Agile/explaining-flow
> browserify src/*.js > dist/index.js && open index.html
> sh: dist/index.js: No such file or directory

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kanban@1.0.0 bundle: `browserify src/*.js > dist/index.js && open index.html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kanban@1.0.0 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by michelgrootjans** [comment]
Thank you for your feedback. I've reproduced the problem.
