### ISSUE TITLE
Bundle script does not work on windows

### ISSUE THREAD

**Issue by lazytesting** [michelgrootjans/explaining-flow#11]
Nice work, I think this simulations are very insightful. 
It would be nice if it would also support Windows, the npm bundle command does not work on windows.

Problems:
1. mkdir -p dist => the -p flag is not supported on windows (but I looks like this is just ignored, so not really an issue )
2. The && chain does not work on windows
3. Calling browserify and open-cli does not work. I think prefixing with npx is the solution (```npx browserify``` works)
4. The wildcard pattern for browserify does not work under windows (https://github.com/browserify/browserify/issues/1170), specifying all filepaths instead will work.

I think it's a bit too much logic to get this working in the npm script, I see two potential solutions.
1. Provide a docker image which can be used to build/run this
2. Move the bundle logic to a separate js file and call that from the npm script.
Let me know if you would like me to do a PR with on of those solutions.

**Comment by michelgrootjans** [comment]
Thank you for your feedback. It's been ages since I worked on windows, so I wasn't aware of this issue.

Indeed, there is too much logic in the script. Could you do a PR to move it all to a separate js file called from the script? It think that might be the most interesting solution.

**Comment by lazytesting** [comment]
Will do!

**Comment by michelgrootjans** [comment]
Solved by merging pull request #12
