### ISSUE TITLE
One suggestion. Show Max and Avg cycle time.

### ISSUE THREAD

**Issue by hallmansm** [michelgrootjans/explaining-flow#30]
I believe the graph shows how high the max cycle time goes, but the comparative metrics at the top shows the Avg, or Mean. The WIP comparison shows real-time as well as Max. It would be great for the Cycle Time pink comparison block to give Avg and Max. Or Mean and Max. 

By the way, I love this thing. This is amazing.

**Comment by michelgrootjans** [comment]
Thank you for the suggestion. This makes the bad scenario's seem even worse ;)
